---
- name: Set color fixes in shell
  blockinfile:
    dest: ~/.config/fish/config.fish
    marker: "# {mark} ANSIBLE MANAGED THEME BLOCK"
    state: present
    block: |
      set fish_color_autosuggestion '#899BA6'
      set fish_pager_color_description '#899BA6'
      set -g theme_color_scheme user

      set -g __color_initial_segment_exit  e6eef3 df8c8c --bold
      set -g __color_initial_segment_su    e6eef3 189303 --bold
      set -g __color_initial_segment_jobs  e6eef3 255e87 --bold

      set -g __color_path                  556873 899ba6
      set -g __color_path_basename         556873 c5d4dd --bold
      set -g __color_path_nowrite          660000 cc9999
      set -g __color_path_nowrite_basename 660000 cc9999 --bold

      set -g __color_repo                  a8ce93 1e272c
      set -g __color_repo_work_tree        dada93 1e272c
      set -g __color_repo_dirty            df8c8c 1e272c
      set -g __color_repo_staged           f2c38f 1e272c
