---
- name: Install the Android NDK (OS X)
  homebrew: name=android-ndk state=present
  when: ansible_os_family == 'Darwin'

- name: Set Android NDK path for Fish shell
  lineinfile: dest=~/.config/fish/config.fish state=present line="set -x ANDROID_NDK /usr/local/opt/android-ndk"
